---
title: "About Me"
---

I am a student at Columbia University Mailman School of Public Health getting my MPH in Epidemiology with a certificate in Applied Biostatistics. I attended University of California, San Diego (UCSD) for my undergrad, where I also majored in public health. During my undergraduate career, I was a part of the Public Health Honors Practium. As a part of this practicum, I worked on a project for the UCSD police department that looked to evaluate the electric scooter guidelines at UCSD. The copy of my group's poster and results can be found [here](https://ph.ucsd.edu/undergrad/undergrad/honors-practicum/The-Struggle-is-Wheel-Evaluation-of-UCSD-Electric-Scooter-Guidelines.pdf). 

Currently, I am also working at the New York City Department of Health and Mental Hygiene (DOHMH) in the Health Economics Outcomes and Research team. I am working there on a project looking at the disparities in mental health hospitalizations between youth experiencing homelessness and youth not experiencing homelessness. 

Before working at the DOHMH, I was working in a psychology lab for a study regarding social anxiety and depression. From that experience, I have become more interested in studying mental health from a public health perspective. 

Outside of work and study,  I am a hobby linguist and enjoy baking.

For more information about my experiences, please email me for my Resume and CV.