---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
data("ny_noaa")

ny_noaa_sub = 
  ny_noaa %>%
    separate(
    col = date, 
    into = c("year", "month", "day"),
    convert = TRUE) %>%
  mutate(
    tmax = as.numeric(tmax),
    tmax = tmax/10,
    tmin = as.numeric(tmin),
    tmin = tmin/10,
    prcp = prcp/10
  ) %>%
  select(id, year, month, prcp, tmax, tmin) %>%
  filter(year == 2010) %>%
  drop_na()

random_stations = 
  ny_noaa_sub %>%
  select(id) %>%
  distinct(id) %>%
  sample_n(50)

ny_noaa_fin = 
  inner_join(random_stations, ny_noaa_sub, by = "id")
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
ny_noaa_fin %>%
  mutate(text_label = str_c("Station ID: ", id, "\nMonth: ", month)) %>% 
  plot_ly(
        x = ~tmax, y = ~tmin, type = "scatter", mode = "markers", 
        color = ~month, text = ~text_label, alpha = 0.5)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
ny_noaa_fin %>%
  mutate(id = fct_reorder(id, tmax)) %>% 
  plot_ly(x = ~id, y = ~tmax, color = ~id, type = "box", colors = "viridis")
```

### Chart C

```{r}
ny_noaa_fin %>%
  count(id) %>%
  mutate(id = fct_reorder(id, n)) %>% 
  plot_ly(x = ~id, y = ~n, color = ~id, type = "bar", colors = "viridis")
```

